### ISSUE TITLE
nodejs is hard-coded to http, does not support https

### ISSUE THREAD

**Issue by RobIsHere** [tus/tus-js-client#44]
tus-js-client/lib.es5/node/request.js

Does a require("http") even if the tus server url is a https://... and fails with a protocol not supported error

We have this requirement, because we must proxy tus through an ssl secured apache.

I tried to simply switch it out for https, but get another error:

```
/var/vinubis/tusnode/tus.js:15
    throw error;
    ^

Error: tus: unexpected response while creating upload
    at Request.xhr.onload (/var/vinubis/tusnode/node_modules/tus-js-client/lib.es5/upload.js:253:36)
    at ClientRequest.<anonymous> (/var/vinubis/tusnode/node_modules/tus-js-client/lib.es5/node/request.js:70:15)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

```

I will try to get out some debuggin info and fix it.
If you have any hints regarding this second error, please let me know :)

**Comment by RobIsHere** [comment]
The Problem was, it did only work with a slash at the end of the endpoint url.
endpoint: "https://my.server.com/upload/tus/",

Didn't work:
endpoint: "https://my.server.com/upload/tus",

**Comment by RobIsHere** [comment]
https://github.com/tus/tus-js-client/pull/45

**Comment by Acconut** [comment]
Thank you a lot for your reporting, the investigation and the immediate patch. :+1:
