### ISSUE TITLE
Crashes when server misbehaves

### ISSUE THREAD

**Issue by mass85** [tus/tus-js-client#81]
Consider a broken tus server:
```
const http = require('http');
let brokenServer = http.createServer((req, res) => {
  res.end('dummy');
 });
brokenServer.listen(8000, 'localhost', () => console.log('started listening'));
```

When tus-js-client in version 1.4.301 attempts to upload something to this server, it crashes with:
```
url.js:81
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at urlParse (url.js:75:5)
    at Url.resolve (url.js:635:29)
    at urlResolve (url.js:631:40)
    at resolveUrl (/home/marcin/packages/file-upload/node_modules/tus-js-client/lib.es5/node/request.js:150:27)
    at Request.xhr.onload (/home/marcin/packages/file-upload/node_modules/tus-js-client/lib.es5/upload.js:328:46)
    at ClientRequest.<anonymous> (/home/marcin/packages/file-upload/node_modules/tus-js-client/lib.es5/node/request.js:84:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
```

HTTP stream:
```
POST / HTTP/1.1
Tus-Resumable: 1.0.0
Upload-Length: 16
Upload-Metadata: filename ZmlsZS0yYjc2Mjk3OTg4ZWM3YzU1NTJiZTFiYjVkOTkwZmQ5YTk4NDdlZGZj,data-type a2Ri,data-format a2Ri,creation-time MTUwMDAyMzMzNjE1NA==,stream-id NTU=,priority NTU=,device-id MA==,device-type ZG5tMw==
Host: localhost:8000
Connection: close
Content-Length: 0

HTTP/1.1 200 OK
Date: Mon, 31 Jul 2017 14:34:30 GMT
Connection: close
Content-Length: 9

dummy
```
As far as I understand it is impossible to catch this exception from code using tus-js-client.

**Comment by Acconut** [comment]
Good catch, the check, whether the Location header is presented in the POST response, is missing (see https://github.com/tus/tus-js-client/blob/master/lib/upload.js#L280). I will take care of this, thank you :)

**Comment by Acconut** [comment]
Sorry, I lost this issue from my radar. However, this commit fixes this problem and now an error is emitted.

**Comment by mass85** [comment]
When do you expect new release?

**Comment by Acconut** [comment]
I am currently fixing an issue with our CI setup but after that I will draft a new release

**Comment by Acconut** [comment]
tus-js-client `1.4.5` is available on NPM
